[dependencies]
num = '0.4.0'
quickersort = '3.0.1'
rand = '0.8.5'
rand_distr = '0.4.3'
rayon = '1.5.1'
special = '0.8.1'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2021'
name = 'scorus'
version = '0.1.0'
[profile.dev]
debug = true
opt-level = 2
