[[test]]
name = 'ptsample_test1'
path = 'tests/ptsample_test1.rs'

[[test]]
name = 'es_test1'
path = 'tests/es_test1.rs'

[dependencies]
num-traits = '0.2.6'
quickersort = '3.0.1'
rand = '0.6.5'
rayon = '1.0.3'
special = '0.8.0'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'scorus'
version = '0.1.0'
[profile.dev]
debug = true
opt-level = 2
