[package]
name = "rsmcmc"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]

[profile.dev]
opt-level = 3

[dependencies]
num = "0.1"
num-traits = "0.1"
rand = "0.3"
scoped_threadpool = "0.1.*"
