[package]
name = "rsmcmc"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]

[profile.dev]
opt-level = 3
debug =true

[dependencies]
num = ">0.1.*"
num-traits = ">0.1.*"
rand = ">0.3.*"
scoped_threadpool = ">0.1.*"
quickersort = ">=3.0.0"

[[example]]
name="sample_bimodal"
path="examples/sample_bimodal.rs"

[[test]]
name="ptsample_test1"
path="tests/ptsample_test1.rs"

[[test]]
name="es_test1"
path="tests/es_test1.rs"
