[dependencies]
num-traits = '0.2.14'
quickersort = '3.0.1'
rand = '0.7.3'
rand_distr = '0.3.0'
rayon = '1.5.0'
special = '0.8.1'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'scorus'
version = '0.1.0'
[profile.dev]
debug = true
opt-level = 2
