[dependencies]
num = '0.4.0'
quickersort = '3.0.1'
rand = '0.8.3'
rand_distr = '0.4.0'
rayon = '1.5.0'
special = '0.8.1'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'scorus'
version = '0.1.0'
edition = "2021"

[profile.dev]
debug = true
opt-level = 2
